# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 26591fd5b0c2f3969f09235ece7ff34a7a9701e4ae961999589cd7ad29e5578d05fec5e2ec612fcba64866ead42d6a01ef1bf2ab414aa8c9ce1f53453760e0c7

test:
  secret_key_base: f160cf4f03f9d8cbcf4a7675749a4fbb64150fb980f70954891e15053063b1184d65cc5d08896857565675a5705a00affbb645d8a1d2b1d44723483dd96fbd12

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
